config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'sessions#new', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout 
  resources :users

  resources :projects
  resources :users, except: :index
  resources :sessions, only: [:new, :create, :destroy]
  resources :donations, only: [:create]

   root 'projects#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  
  belongs_to :reward
  belongs_to :backer, foreign_key: 'user_id', class_name: 'User'

  delegate :project, :to => :reward

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :rewards
  has_many :donations, through: :rewards
  has_many :backers, through: :donations, class_name: 'User'
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  accepts_nested_attributes_for :rewards, allow_destroy: true
  validates :name, presence: true
  validates :goal, presence: true

  def current_funding
  	total = 0
  	donations.each do |donation|
      if donation.amount
  		  total += donation.amount
      end
  	end
  	total
  end

  def funding_left
     self.goal - current_funding
  end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project
  has_many :donations
  has_many :rewards, through: :donations

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }, on: :create
  validates :password, length: { minimum: 3, allow_blank: true }, on: :update
  validates :password, confirmation: true
  validates :password_confirmation, presence: true, on: :create

  validates :email, uniqueness: true

  has_many :owned_projects, class_name: 'Project'
  has_many :donations
  has_many :rewards, :through => :donations
  has_many :backed_projects, :through => :rewards, :source => :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  def create
  	@donation = Donation.new(donation_params)
  	@donation.user_id = current_user.id
  	@project = @donation.project
  	if @donation.save
  		redirect_to project_url(@project)
  	else
  		render "/projects/show"
  	end
  end

  private

  def donation_params
  	params.require(:donation).permit(:reward_id, :amount)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = if params[:search]
			Project.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}")
		else
			@projects = Project.all
		end
		respond_to do |format|
			format.html
			format.js
		end
	end
	

def show
	@project = Project.find(params[:id])
end

def new
	@project = Project.new	

end

def create
	@project = Project.new(project_params)
	@project.user_id = current_user.id
	if @project.save

		redirect_to projects_url
	else
		render :new
	end 
end

def edit
	@project = current_user.owned_projects.find(params[:id])
end

def update
	@project = Project.find(params[:id])

	if @project.update_attributes(project_params)
		redirect_to "/projects/#{@project.id}"
	else
		render :edit
	end
end

def destroy
	Project.find(params[:id]).destroy
	redirect_to projects_url, :flash => { :success => "Project destroyed." }
end


private
def project_params
	params.require(:project).permit(:name, :description, :goal, :start_date, :end_date, rewards_attributes: [:id, :description, :amount, :_destroy], donations_attributes: [:reward_id, :amount, :_destroy])

end	

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
     if @user = login(params[:email], params[:password])
      redirect_back_or_to( @user, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

def destroy
  logout
  redirect_to(root_url, notice: 'Logged out!')
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
      user_params.delete(:password) if (user_params[:password].blank?)
      user_params.delete(:password_confirmation) if (user_params[:password_confirmation].blank?)
    respond_to do |format|
      
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donation_helper.rb
module DonationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/donations/create.html.erb
<h1>Donation#create</h1>
<p>Find me in app/views/donation/create.html.erb</p>

app/views/donations/destroy.html.erb
<h1>Donation#destroy</h1>
<p>Find me in app/views/donation/destroy.html.erb</p>

app/views/donations/new.html.erb
<h1>Donation#new</h1>
<p>Find me in app/views/donation/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="nav">

    <% if current_user %>
      <%= link_to 'Your Profile', user_path(current_user.id) %> |
      <%= link_to 'Edit Profile', edit_user_path(current_user.id) %> |
      <%= link_to 'Logout', :logout, method: :post %>
    <% else %>  
      <%= link_to 'Register', new_user_path %>
      <%= link_to 'Login', :login %>
    <% end -%>
  </div>

  <div>
    <p id="notice"><%= flash[:notice]%></p>
    <p id="alert"><%= flash[:alert]%></p>
  </div>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :goal %><br />
    <%= f.number_field :goal %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  

  <div id="rewards">
    <h3>Rewards</h3>
  
    <%= f.fields_for :rewards do |rewards_form| %>
      <%= render 'reward_fields', f: rewards_form %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add reward', f, :rewards %>
    </div>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<%= link_to project_path(project.id) do %>

  <h3><%= project.name%></h3>
  <% end -%>
Description: <%= project.description %><br />
Goal: <%= project.goal%><br />
Start Date: <%= project.start_date%><br />
End Date: <%= project.end_date%> <br />
Current Funding: $<%= project.current_funding %> <br />
Amount Left: <%= project.funding_left %> <br>



<%= link_to "Show", project %>

app/views/projects/_reward_fields.html.erb
<div class="nested-fields">
	<div class="field">
		<%= f.label :description %>:<br />
		<%= f.text_area :description %><br />
	</div>
	<div class="field">
		<%= f.label :amount %> $<br />
		<%= f.number_field :amount %><br />
	</div>
	<%= link_to_remove_association "remove reward", f %>
</div>

app/views/projects/edit.html.erb
<%= link_to "Back to Project", project_url %>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>CrowdFUNder Projects</h1>

<%= link_to "Create a New Project!", new_project_url %>

<%= form_tag projects_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search], :placeholder => 'Search Project Name' %>
  <%= submit_tag "Search" %>
<% end -%>

<div id="projects">
  <%= render @projects %>
</div>

app/views/projects/index.js.erb
<% if params[:page] %>
  $('#projects').append("<%= j(render @projects) %>")
  <% else %>
  $('#projects').html("<%= j(render @projects) %>")
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_url %>

app/views/projects/show.html.erb
<%= link_to "Back to Projects", projects_url %>

<p>
<h1><%= @project[:name]%></h1>
Description: <%= @project[:description]%><br />
Goal: <%= @project[:goal]%><br />
Start Date: <%= @project.start_date%><br />
End Date: <%= @project[:end_date]%>  <br />
Current Total: $<%# @project.current_funding %> <br>
Amount Left: $<%# @project.funding_left %> <br>
</p>

<h3>Project Rewards</h3>
<% @project.rewards.each do |reward| %>
	<%= reward.description %> <br />
	$<%= reward.amount %><br />
	<%= form_for reward.donations.build(:amount => reward.amount) do |f| %>
		<%= f.hidden_field :reward_id %>
		<%= f.hidden_field :amount %>
		<%= f.submit "Donate!" %>
	<% end %>
<% end %>

<%= link_to "Back to Projects", projects_url %> | <%= link_to "Edit", edit_project_path(@project) %> | 

<%= link_to 'Destroy', @project, method: :delete, date:{confirm: 'Are you sure?'}%>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
</div>
<div class="field">
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %>
</div>

<div class="field">
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br>
  <%= f.password_field :password %>
</div>

<div class="field">
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>



<%= link_to 'Browse All Projects', projects_url %> <br>

<%= link_to "Create a New Project", new_project_url %> <br>

<h3>Your Current Projects</h3>

<% current_user.owned_projects.each do |project| %>
  <%=link_to project.name, project_path %> <br>
  <%= project.description %> <br>
<% end -%>

<h3>Your Backed Projects</h3>

<% current_user.backed_projects.each do |project| %>
  <%=link_to project.name, project_path %> <br>
  <%= project.description %> <br>
<% end -%>

<h3>Your Donations</h3>

<% current_user.donations.each do |donation| %>
  <%= donation.amount %> <br>
<% end -%>